error check

diff --git a/s3/bashscripts/put-object b/s3/bashscripts/put-object
--- a/s3/bashscripts/put-object
+++ b/s3/bashscripts/put-object
@@ -1,5 +1,7 @@
 #!/usr/bin/env bash
 echo "== put-object"
+#make sure to exit if any command returns a non-zero status
+set -e
 
 # Check for bucket name
 if [ -z "$1" ]; then
